[build]
  command="npm run build"
  publish="dist/provolt/browser"

[build.environment]
  SITEMAP_BASE_URL = "https://provoltelectricalservices.com"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false